jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralasndOtherSymbo$'

server:
  port: 8081
#  Disable whitelabel error page class org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
#  error:
#    whitelabel:
#      enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/supportportal
    password: RoOtPass
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  #Instead of returning 'White label error' it will be throw exception
#  mvc:
#    throw-exception-if-no-handler-found: true
#  web:
##  resources: //for spring version >=2.4 https://dev.to/send2abhishek/how-to-customise-white-label-error-in-spring-boot-672
#    add-mappings: false

# White label render method located in ErrorMvcAutoConfiguration.StaticView.render