server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/supportportal
    password: RoOtPass
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
